import { TMockPhones } from "@/types/TMockPhones"

export const mockPhones = [
    {
        name: 'Apple iPhone 12',
        id: 1, 
        manufacturer: 'Apple', 
        releaseYear: 2020,
        screenDiagonal: 6.1,
        сountryOfOrigin: 'Китай',
        memoryCapacity: 128,
        screenRefreshRate: 60,
        NFC: false,
        ESIM: true,
        wirelessСharging: true,
        cost: 81990,
        image: '/images/ApplePhone12.png'
    }, 
    {
        name: 'Xiaomi Mi 11 Lite',
        id: 2, 
        manufacturer: 'Xiaomi', 
        releaseYear: 2021,
        screenDiagonal: 6.55,
        сountryOfOrigin: 'Китай',
        memoryCapacity: 128,
        screenRefreshRate: 90,
        NFC: true,
        ESIM: true,
        wirelessСharging: false,
        cost: 27490,
        image: '/images/XiaomiMi11Lite.jpg'
    },
    {
        name: 'Samsung Galaxy A72',
        id: 3, 
        manufacturer: 'Samsung', 
        releaseYear: 2021,
        screenDiagonal: 6.7,
        сountryOfOrigin: 'Вьетнам',
        memoryCapacity: 128,
        screenRefreshRate: 90,
        NFC: true,
        ESIM: false,
        wirelessСharging: true,
        cost: 32890,
        image: '/images/SamsungGalaxyA72.jpg'
    },
    {
        name: 'Samsung Galaxy S21',
        id: 4, 
        manufacturer: 'Samsung', 
        releaseYear: 2021,
        screenDiagonal: 6.2,
        сountryOfOrigin: 'Вьетнам',
        memoryCapacity: 256,
        screenRefreshRate: 120,
        NFC: true,
        ESIM: true,
        wirelessСharging: true,
        cost: 25790,
        image: '/images/SamsungGalaxyS21.png'
    }, 
    {
        name: 'Apple iPhone Xr',
        id: 5, 
        manufacturer: 'Apple', 
        releaseYear: 2021,
        screenDiagonal: 6.1,
        сountryOfOrigin: 'Китай',
        memoryCapacity: 128,
        screenRefreshRate: 60,
        NFC: true,
        ESIM: true,
        wirelessСharging: true,
        cost: 23890,
        image: '/images/AppleIPhoneXr.png'
    },
    {
        name: 'Realme 8 Pro',
        id: 6, 
        manufacturer: 'Realme', 
        releaseYear: 2020,
        screenDiagonal: 6.5,
        сountryOfOrigin: 'Китай',
        memoryCapacity: 128,
        screenRefreshRate: 60,
        NFC: true,
        ESIM: false,
        wirelessСharging: false,
        cost: 13187,
        image: '/images/Realme8Pro.png'
    },
    {
        name: 'Apple iPhone 10',
        id: 7, 
        manufacturer: 'Apple', 
        releaseYear: 2018,
        screenDiagonal: 6.1,
        сountryOfOrigin: 'Китай',
        memoryCapacity: 128,
        screenRefreshRate: 60,
        NFC: false,
        ESIM: true,
        wirelessСharging: true,
        cost: 25990,
        image: '/images/ApplePhone12.png'
    }, 
    {
        name: 'Xiaomi Mi 10 Mini',
        id: 8, 
        manufacturer: 'Xiaomi', 
        releaseYear: 2019,
        screenDiagonal: 6.55,
        сountryOfOrigin: 'Китай',
        memoryCapacity: 128,
        screenRefreshRate: 60,
        NFC: true,
        ESIM: true,
        wirelessСharging: false,
        cost: 17490,
        image: '/images/XiaomiMi11Lite.jpg'
    },
    {
        name: 'Samsung Galaxy K9',
        id: 9, 
        manufacturer: 'Samsung', 
        releaseYear: 2018,
        screenDiagonal: 6.7,
        сountryOfOrigin: 'Вьетнам',
        memoryCapacity: 128,
        screenRefreshRate: 60,
        NFC: true,
        ESIM: false,
        wirelessСharging: true,
        cost: 22890,
        image: '/images/SamsungGalaxyA72.jpg'
    },
    {
        name: 'Samsung Galaxy S15',
        id: 10, 
        manufacturer: 'Samsung', 
        releaseYear: 2018,
        screenDiagonal: 6.2,
        сountryOfOrigin: 'Вьетнам',
        memoryCapacity: 128,
        screenRefreshRate: 60,
        NFC: true,
        ESIM: true,
        wirelessСharging: true,
        cost: 15790,
        image: '/images/SamsungGalaxyS21.png'
    }, 
    {
        name: 'Apple iPhone S13',
        id: 11, 
        manufacturer: 'Apple', 
        releaseYear: 2021,
        screenDiagonal: 6.1,
        сountryOfOrigin: 'Китай',
        memoryCapacity: 128,
        screenRefreshRate: 60,
        NFC: true,
        ESIM: true,
        wirelessСharging: true,
        cost: 53890,
        image: '/images/AppleIPhoneXr.png'
    },
    {
        name: 'Realme 10 Pro',
        id: 12, 
        manufacturer: 'Realme', 
        releaseYear: 2022,
        screenDiagonal: 6.5,
        сountryOfOrigin: 'Китай',
        memoryCapacity: 128,
        screenRefreshRate: 90,
        NFC: true,
        ESIM: true,
        wirelessСharging: true,
        cost: 53187,
        image: '/images/Realme8Pro.png'
    }
]